package app.marysia.skel.config;

import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.DatabaseMetaData;

/**
 * Idempotent schema bootstrap for the wrapper-shared backend stack.
 *
 * <p>Creates the {@code users}, {@code categories}, {@code items}, and
 * {@code react_state} tables {@code IF NOT EXISTS} on application
 * startup so a freshly-generated wrapper boots with no Flyway /
 * Liquibase / migrations step required. The schema mirrors the
 * django-bolt skeleton's {@code app/models.py} so a single
 * {@code _shared/db.sqlite3} can be read by either backend without
 * translation.
 *
 * <p>SQL dialect is detected from the JDBC URL because the wrapper
 * may target SQLite (the default), H2, or Postgres — column types
 * differ slightly between them (e.g. {@code INTEGER PRIMARY KEY
 * AUTOINCREMENT} for SQLite vs {@code BIGSERIAL} for Postgres). The
 * H2 case is treated as SQLite-compatible because both honour
 * {@code AUTOINCREMENT}-style integer primary keys.
 */
@Component
public class SchemaInitializer {

    private static final Logger log = LoggerFactory.getLogger(SchemaInitializer.class);

    private final JdbcTemplate jdbc;
    private final DataSource dataSource;
    private final PasswordEncoder passwordEncoder;

    public SchemaInitializer(JdbcTemplate jdbc, DataSource dataSource, PasswordEncoder passwordEncoder) {
        this.jdbc = jdbc;
        this.dataSource = dataSource;
        this.passwordEncoder = passwordEncoder;
    }

    @PostConstruct
    public void init() {
        Dialect dialect = detectDialect();
        log.info("Bootstrapping wrapper-shared schema with dialect={}", dialect);
        createUsers(dialect);
        createCategories(dialect);
        createItems(dialect);
        addCategoryIdToItems(dialect);
        createReactState(dialect);
        createCatalogItems(dialect);
        createOrders(dialect);
        createOrderLines(dialect);
        createOrderAddresses(dialect);
        seedDefaultAccounts(jdbc, passwordEncoder);
    }

    private void createUsers(Dialect dialect) {
        String sql = switch (dialect) {
            case POSTGRES -> """
                CREATE TABLE IF NOT EXISTS users (
                    id            BIGSERIAL PRIMARY KEY,
                    username      TEXT NOT NULL UNIQUE,
                    email         TEXT NOT NULL,
                    password_hash TEXT NOT NULL,
                    is_superuser  BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at    TIMESTAMP NOT NULL DEFAULT NOW()
                )
                """;
            case H2 -> """
                CREATE TABLE IF NOT EXISTS users (
                    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username      VARCHAR(255) NOT NULL UNIQUE,
                    email         VARCHAR(255) NOT NULL,
                    password_hash VARCHAR(255) NOT NULL,
                    is_superuser  BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """;
            case SQLITE -> """
                CREATE TABLE IF NOT EXISTS users (
                    id            INTEGER PRIMARY KEY AUTOINCREMENT,
                    username      TEXT NOT NULL UNIQUE,
                    email         TEXT NOT NULL,
                    password_hash TEXT NOT NULL,
                    is_superuser  INTEGER NOT NULL DEFAULT 0,
                    created_at    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """;
        };
        jdbc.execute(sql);
    }

    private void createCategories(Dialect dialect) {
        String sql = switch (dialect) {
            case POSTGRES -> """
                CREATE TABLE IF NOT EXISTS categories (
                    id          BIGSERIAL PRIMARY KEY,
                    name        TEXT NOT NULL UNIQUE,
                    description TEXT,
                    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
                    updated_at  TIMESTAMP NOT NULL DEFAULT NOW()
                )
                """;
            case H2 -> """
                CREATE TABLE IF NOT EXISTS categories (
                    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name        VARCHAR(255) NOT NULL UNIQUE,
                    description VARCHAR(2048),
                    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """;
            case SQLITE -> """
                CREATE TABLE IF NOT EXISTS categories (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    name        TEXT NOT NULL UNIQUE,
                    description TEXT,
                    created_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """;
        };
        jdbc.execute(sql);
    }

    private void createItems(Dialect dialect) {
        String sql = switch (dialect) {
            case POSTGRES -> """
                CREATE TABLE IF NOT EXISTS items (
                    id            BIGSERIAL PRIMARY KEY,
                    name          TEXT NOT NULL,
                    description   TEXT,
                    is_completed  BOOLEAN NOT NULL DEFAULT FALSE,
                    category_id   BIGINT REFERENCES categories(id) ON DELETE SET NULL,
                    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
                    updated_at    TIMESTAMP NOT NULL DEFAULT NOW()
                )
                """;
            case H2 -> """
                CREATE TABLE IF NOT EXISTS items (
                    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name          VARCHAR(255) NOT NULL,
                    description   VARCHAR(2048),
                    is_completed  BOOLEAN NOT NULL DEFAULT FALSE,
                    category_id   BIGINT,
                    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
                )
                """;
            case SQLITE -> """
                CREATE TABLE IF NOT EXISTS items (
                    id            INTEGER PRIMARY KEY AUTOINCREMENT,
                    name          TEXT NOT NULL,
                    description   TEXT,
                    is_completed  INTEGER NOT NULL DEFAULT 0,
                    category_id   INTEGER REFERENCES categories(id) ON DELETE SET NULL,
                    created_at    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """;
        };
        jdbc.execute(sql);
    }

    /**
     * Add {@code category_id} to pre-existing {@code items} tables that
     * were created before the categories feature landed. {@code ALTER
     * TABLE ... ADD COLUMN IF NOT EXISTS} is not universally supported
     * (SQLite only gained it in 3.35), so we catch the "column already
     * exists" exception and treat it as a no-op.
     */
    private void addCategoryIdToItems(Dialect dialect) {
        try {
            jdbc.execute("ALTER TABLE items ADD COLUMN category_id "
                + (dialect == Dialect.SQLITE ? "INTEGER" : "BIGINT"));
        } catch (Exception e) {
            // Column already exists — expected on fresh databases where
            // createItems already included category_id.
            log.debug("category_id column already exists on items (safe to ignore): {}", e.toString());
        }
    }

    private void createReactState(Dialect dialect) {
        String sql = switch (dialect) {
            case POSTGRES -> """
                CREATE TABLE IF NOT EXISTS react_state (
                    id          BIGSERIAL PRIMARY KEY,
                    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    state_key   TEXT NOT NULL,
                    state_value TEXT NOT NULL,
                    updated_at  TIMESTAMP NOT NULL DEFAULT NOW(),
                    UNIQUE (user_id, state_key)
                )
                """;
            case H2 -> """
                CREATE TABLE IF NOT EXISTS react_state (
                    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id     BIGINT NOT NULL,
                    state_key   VARCHAR(255) NOT NULL,
                    state_value CLOB NOT NULL,
                    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE (user_id, state_key),
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                )
                """;
            case SQLITE -> """
                CREATE TABLE IF NOT EXISTS react_state (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id     INTEGER NOT NULL,
                    state_key   TEXT NOT NULL,
                    state_value TEXT NOT NULL,
                    updated_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE (user_id, state_key),
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                )
                """;
        };
        jdbc.execute(sql);
    }

    private void createCatalogItems(Dialect dialect) {
        String sql = switch (dialect) {
            case POSTGRES -> """
                CREATE TABLE IF NOT EXISTS catalog_items (
                    id          BIGSERIAL PRIMARY KEY,
                    name        TEXT NOT NULL,
                    description TEXT DEFAULT '',
                    price       DOUBLE PRECISION NOT NULL,
                    category    TEXT DEFAULT '',
                    available   BOOLEAN DEFAULT TRUE
                )
                """;
            case H2 -> """
                CREATE TABLE IF NOT EXISTS catalog_items (
                    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name        VARCHAR(255) NOT NULL,
                    description VARCHAR(2048) DEFAULT '',
                    price       DOUBLE NOT NULL,
                    category    VARCHAR(255) DEFAULT '',
                    available   BOOLEAN DEFAULT TRUE
                )
                """;
            case SQLITE -> """
                CREATE TABLE IF NOT EXISTS catalog_items (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    name        TEXT NOT NULL,
                    description TEXT DEFAULT '',
                    price       REAL NOT NULL,
                    category    TEXT DEFAULT '',
                    available   INTEGER DEFAULT 1
                )
                """;
        };
        jdbc.execute(sql);
    }

    private void createOrders(Dialect dialect) {
        String sql = switch (dialect) {
            case POSTGRES -> """
                CREATE TABLE IF NOT EXISTS orders (
                    id           BIGSERIAL PRIMARY KEY,
                    user_id      BIGINT NOT NULL REFERENCES users(id),
                    status       TEXT DEFAULT 'draft',
                    created_at   TIMESTAMP DEFAULT NOW(),
                    submitted_at TIMESTAMP,
                    wait_minutes INTEGER,
                    feedback     TEXT
                )
                """;
            case H2 -> """
                CREATE TABLE IF NOT EXISTS orders (
                    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id      BIGINT NOT NULL,
                    status       VARCHAR(50) DEFAULT 'draft',
                    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    submitted_at TIMESTAMP,
                    wait_minutes INTEGER,
                    feedback     VARCHAR(2048),
                    FOREIGN KEY (user_id) REFERENCES users(id)
                )
                """;
            case SQLITE -> """
                CREATE TABLE IF NOT EXISTS orders (
                    id           INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id      INTEGER NOT NULL REFERENCES users(id),
                    status       TEXT DEFAULT 'draft',
                    created_at   TEXT DEFAULT (datetime('now')),
                    submitted_at TEXT,
                    wait_minutes INTEGER,
                    feedback     TEXT
                )
                """;
        };
        jdbc.execute(sql);
    }

    private void createOrderLines(Dialect dialect) {
        String sql = switch (dialect) {
            case POSTGRES -> """
                CREATE TABLE IF NOT EXISTS order_lines (
                    id              BIGSERIAL PRIMARY KEY,
                    order_id        BIGINT NOT NULL REFERENCES orders(id),
                    catalog_item_id BIGINT NOT NULL REFERENCES catalog_items(id),
                    quantity        INTEGER DEFAULT 1,
                    unit_price      DOUBLE PRECISION DEFAULT 0.0
                )
                """;
            case H2 -> """
                CREATE TABLE IF NOT EXISTS order_lines (
                    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    order_id        BIGINT NOT NULL,
                    catalog_item_id BIGINT NOT NULL,
                    quantity        INTEGER DEFAULT 1,
                    unit_price      DOUBLE DEFAULT 0.0,
                    FOREIGN KEY (order_id) REFERENCES orders(id),
                    FOREIGN KEY (catalog_item_id) REFERENCES catalog_items(id)
                )
                """;
            case SQLITE -> """
                CREATE TABLE IF NOT EXISTS order_lines (
                    id              INTEGER PRIMARY KEY AUTOINCREMENT,
                    order_id        INTEGER NOT NULL REFERENCES orders(id),
                    catalog_item_id INTEGER NOT NULL REFERENCES catalog_items(id),
                    quantity        INTEGER DEFAULT 1,
                    unit_price      REAL DEFAULT 0.0
                )
                """;
        };
        jdbc.execute(sql);
    }

    private void createOrderAddresses(Dialect dialect) {
        String sql = switch (dialect) {
            case POSTGRES -> """
                CREATE TABLE IF NOT EXISTS order_addresses (
                    id       BIGSERIAL PRIMARY KEY,
                    order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id),
                    street   TEXT NOT NULL,
                    city     TEXT NOT NULL,
                    zip_code TEXT NOT NULL,
                    phone    TEXT DEFAULT '',
                    notes    TEXT DEFAULT ''
                )
                """;
            case H2 -> """
                CREATE TABLE IF NOT EXISTS order_addresses (
                    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    order_id BIGINT NOT NULL UNIQUE,
                    street   VARCHAR(512) NOT NULL,
                    city     VARCHAR(255) NOT NULL,
                    zip_code VARCHAR(20) NOT NULL,
                    phone    VARCHAR(50) DEFAULT '',
                    notes    VARCHAR(2048) DEFAULT '',
                    FOREIGN KEY (order_id) REFERENCES orders(id)
                )
                """;
            case SQLITE -> """
                CREATE TABLE IF NOT EXISTS order_addresses (
                    id       INTEGER PRIMARY KEY AUTOINCREMENT,
                    order_id INTEGER NOT NULL UNIQUE REFERENCES orders(id),
                    street   TEXT NOT NULL,
                    city     TEXT NOT NULL,
                    zip_code TEXT NOT NULL,
                    phone    TEXT DEFAULT '',
                    notes    TEXT DEFAULT ''
                )
                """;
        };
        jdbc.execute(sql);
    }

    private void seedDefaultAccounts(JdbcTemplate jdbc, PasswordEncoder encoder) {
        String[][] accounts = {
            {env("USER_LOGIN", "user"), env("USER_EMAIL", "user@example.com"), env("USER_PASSWORD", "secret"), "false"},
            {env("SUPERUSER_LOGIN", "admin"), env("SUPERUSER_EMAIL", "admin@example.com"), env("SUPERUSER_PASSWORD", "secret"), "true"},
        };
        for (String[] acct : accounts) {
            String username = acct[0], email = acct[1], password = acct[2];
            boolean isSuperuser = Boolean.parseBoolean(acct[3]);
            Integer count = jdbc.queryForObject("SELECT COUNT(*) FROM users WHERE username = ?", Integer.class, username);
            if (count != null && count > 0) {
                log.info("[seed] Default user '{}' already exists", username);
                continue;
            }
            jdbc.update("INSERT INTO users (username, email, password_hash, is_superuser) VALUES (?, ?, ?, ?)",
                username, email, encoder.encode(password), isSuperuser);
            log.info("[seed] Created default user '{}'", username);
        }
    }

    private static String env(String key, String fallback) {
        String val = System.getenv(key);
        return (val != null && !val.isBlank()) ? val : fallback;
    }

    private Dialect detectDialect() {
        try (Connection conn = dataSource.getConnection()) {
            DatabaseMetaData md = conn.getMetaData();
            String name = md.getDatabaseProductName().toLowerCase();
            if (name.contains("postgres")) return Dialect.POSTGRES;
            if (name.contains("h2")) return Dialect.H2;
            if (name.contains("sqlite")) return Dialect.SQLITE;
            return Dialect.SQLITE;
        } catch (Exception e) {
            log.warn("Could not detect database dialect, defaulting to SQLite-compatible: {}", e.toString());
            return Dialect.SQLITE;
        }
    }

    private enum Dialect { SQLITE, H2, POSTGRES }
}
