apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-svc
  namespace:  {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}-name
    app.kubernetes.io/part-of: example-project
    app.kubernetes.io/component: svc
spec:
  ports:
    - port: {{ .Values.svc.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/part-of: example-project
    app.kubernetes.io/component: pod
