package com.example.skel.config;

import jakarta.annotation.PostConstruct;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.DatabaseMetaData;

/**
 * Idempotent schema bootstrap for the wrapper-shared backend stack.
 *
 * <p>Creates the {@code users}, {@code categories}, {@code items}, and
 * {@code react_state} tables {@code IF NOT EXISTS} on application
 * startup so a freshly-generated wrapper boots with no Flyway /
 * Liquibase / migrations step required. The schema mirrors the
 * django-bolt skeleton's {@code app/models.py} so a single
 * {@code _shared/db.sqlite3} can be read by either backend without
 * translation.
 *
 * <p>SQL dialect is detected from the JDBC URL because the wrapper
 * may target SQLite (the default), H2, or Postgres — column types
 * differ slightly between them (e.g. {@code INTEGER PRIMARY KEY
 * AUTOINCREMENT} for SQLite vs {@code BIGSERIAL} for Postgres). The
 * H2 case is treated as SQLite-compatible because both honour
 * {@code AUTOINCREMENT}-style integer primary keys.
 */
@Component
public class SchemaInitializer {

    private static final Logger log = LoggerFactory.getLogger(SchemaInitializer.class);

    private final JdbcTemplate jdbc;
    private final DataSource dataSource;

    public SchemaInitializer(JdbcTemplate jdbc, DataSource dataSource) {
        this.jdbc = jdbc;
        this.dataSource = dataSource;
    }

    @PostConstruct
    public void init() {
        Dialect dialect = detectDialect();
        log.info("Bootstrapping wrapper-shared schema with dialect={}", dialect);
        createUsers(dialect);
        createCategories(dialect);
        createItems(dialect);
        addCategoryIdToItems(dialect);
        createReactState(dialect);
    }

    private void createUsers(Dialect dialect) {
        String sql = switch (dialect) {
            case POSTGRES -> """
                CREATE TABLE IF NOT EXISTS users (
                    id            BIGSERIAL PRIMARY KEY,
                    username      TEXT NOT NULL UNIQUE,
                    email         TEXT NOT NULL,
                    password_hash TEXT NOT NULL,
                    created_at    TIMESTAMP NOT NULL DEFAULT NOW()
                )
                """;
            case H2 -> """
                CREATE TABLE IF NOT EXISTS users (
                    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    username      VARCHAR(255) NOT NULL UNIQUE,
                    email         VARCHAR(255) NOT NULL,
                    password_hash VARCHAR(255) NOT NULL,
                    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """;
            case SQLITE -> """
                CREATE TABLE IF NOT EXISTS users (
                    id            INTEGER PRIMARY KEY AUTOINCREMENT,
                    username      TEXT NOT NULL UNIQUE,
                    email         TEXT NOT NULL,
                    password_hash TEXT NOT NULL,
                    created_at    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """;
        };
        jdbc.execute(sql);
    }

    private void createCategories(Dialect dialect) {
        String sql = switch (dialect) {
            case POSTGRES -> """
                CREATE TABLE IF NOT EXISTS categories (
                    id          BIGSERIAL PRIMARY KEY,
                    name        TEXT NOT NULL UNIQUE,
                    description TEXT,
                    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
                    updated_at  TIMESTAMP NOT NULL DEFAULT NOW()
                )
                """;
            case H2 -> """
                CREATE TABLE IF NOT EXISTS categories (
                    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name        VARCHAR(255) NOT NULL UNIQUE,
                    description VARCHAR(2048),
                    created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """;
            case SQLITE -> """
                CREATE TABLE IF NOT EXISTS categories (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    name        TEXT NOT NULL UNIQUE,
                    description TEXT,
                    created_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """;
        };
        jdbc.execute(sql);
    }

    private void createItems(Dialect dialect) {
        String sql = switch (dialect) {
            case POSTGRES -> """
                CREATE TABLE IF NOT EXISTS items (
                    id            BIGSERIAL PRIMARY KEY,
                    name          TEXT NOT NULL,
                    description   TEXT,
                    is_completed  BOOLEAN NOT NULL DEFAULT FALSE,
                    category_id   BIGINT REFERENCES categories(id) ON DELETE SET NULL,
                    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
                    updated_at    TIMESTAMP NOT NULL DEFAULT NOW()
                )
                """;
            case H2 -> """
                CREATE TABLE IF NOT EXISTS items (
                    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name          VARCHAR(255) NOT NULL,
                    description   VARCHAR(2048),
                    is_completed  BOOLEAN NOT NULL DEFAULT FALSE,
                    category_id   BIGINT,
                    created_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at    TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
                )
                """;
            case SQLITE -> """
                CREATE TABLE IF NOT EXISTS items (
                    id            INTEGER PRIMARY KEY AUTOINCREMENT,
                    name          TEXT NOT NULL,
                    description   TEXT,
                    is_completed  INTEGER NOT NULL DEFAULT 0,
                    category_id   INTEGER REFERENCES categories(id) ON DELETE SET NULL,
                    created_at    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at    TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """;
        };
        jdbc.execute(sql);
    }

    /**
     * Add {@code category_id} to pre-existing {@code items} tables that
     * were created before the categories feature landed. {@code ALTER
     * TABLE ... ADD COLUMN IF NOT EXISTS} is not universally supported
     * (SQLite only gained it in 3.35), so we catch the "column already
     * exists" exception and treat it as a no-op.
     */
    private void addCategoryIdToItems(Dialect dialect) {
        try {
            jdbc.execute("ALTER TABLE items ADD COLUMN category_id "
                + (dialect == Dialect.SQLITE ? "INTEGER" : "BIGINT"));
        } catch (Exception e) {
            // Column already exists — expected on fresh databases where
            // createItems already included category_id.
            log.debug("category_id column already exists on items (safe to ignore): {}", e.toString());
        }
    }

    private void createReactState(Dialect dialect) {
        String sql = switch (dialect) {
            case POSTGRES -> """
                CREATE TABLE IF NOT EXISTS react_state (
                    id          BIGSERIAL PRIMARY KEY,
                    user_id     BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                    state_key   TEXT NOT NULL,
                    state_value TEXT NOT NULL,
                    updated_at  TIMESTAMP NOT NULL DEFAULT NOW(),
                    UNIQUE (user_id, state_key)
                )
                """;
            case H2 -> """
                CREATE TABLE IF NOT EXISTS react_state (
                    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    user_id     BIGINT NOT NULL,
                    state_key   VARCHAR(255) NOT NULL,
                    state_value CLOB NOT NULL,
                    updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE (user_id, state_key),
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                )
                """;
            case SQLITE -> """
                CREATE TABLE IF NOT EXISTS react_state (
                    id          INTEGER PRIMARY KEY AUTOINCREMENT,
                    user_id     INTEGER NOT NULL,
                    state_key   TEXT NOT NULL,
                    state_value TEXT NOT NULL,
                    updated_at  TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE (user_id, state_key),
                    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
                )
                """;
        };
        jdbc.execute(sql);
    }

    private Dialect detectDialect() {
        try (Connection conn = dataSource.getConnection()) {
            DatabaseMetaData md = conn.getMetaData();
            String name = md.getDatabaseProductName().toLowerCase();
            if (name.contains("postgres")) return Dialect.POSTGRES;
            if (name.contains("h2")) return Dialect.H2;
            if (name.contains("sqlite")) return Dialect.SQLITE;
            return Dialect.SQLITE;
        } catch (Exception e) {
            log.warn("Could not detect database dialect, defaulting to SQLite-compatible: {}", e.toString());
            return Dialect.SQLITE;
        }
    }

    private enum Dialect { SQLITE, H2, POSTGRES }
}
